export const UPDATE_CREDENTIALS = "UPDATE_CREDENTIALS";
export const CHECK_GUARD_REQUEST = "CHECK_GUARD_REQUEST";
export const CHECK_GUARD_SUCCESS = "CHECK_GUARD_SUCCESS";
export const CHECK_GUARD_FAILURE = "CHECK_GUARD_FAILURE";
export const CREATE_GUARD_REQUEST = "CREATE_GUARD_REQUEST";
export const CREATE_GUARD_SUCCESS = "CREATE_GUARD_SUCCESS";
export const CREATE_GUARD_FAILURE = "CREATE_GUARD_FAILURE";
