export const FETCH_DISCUSSIONS_ALL_REQUEST = "FETCH_DISCUSSIONS_ALL_REQUEST";
export const FETCH_DISCUSSIONS_ALL_SUCCESS = "FETCH_DISCUSSIONS_ALL_SUCCESS";
export const FETCH_DISCUSSIONS_ALL_FAILURE = "FETCH_DISCUSSIONS_ALL_FAILURE";

export const FETCH_DISCUSSIONS_OWNER_REQUEST = "FETCH_DISCUSSIONS_OWNER_REQUEST";
export const FETCH_DISCUSSIONS_OWNER_SUCCESS = "FETCH_DISCUSSIONS_OWNER_SUCCESS";
export const FETCH_DISCUSSIONS_OWNER_FAILURE = "FETCH_DISCUSSIONS_OWNER_FAILURE";

export const FETCH_DISCUSSIONS_TRAVELLER_REQUEST = "FETCH_DISCUSSIONS_TRAVELLER_REQUEST";
export const FETCH_DISCUSSIONS_TRAVELLER_SUCCESS = "FETCH_DISCUSSIONS_TRAVELLER_SUCCESS";
export const FETCH_DISCUSSIONS_TRAVELLER_FAILURE = "FETCH_DISCUSSIONS_TRAVELLER_FAILURE";

export const FETCH_CURRENT_DISCUSSION_REQUEST = "FETCH_CURRENT_DISCUSSION_REQUEST";
export const FETCH_CURRENT_DISCUSSION_SUCCESS = "FETCH_CURRENT_DISCUSSION_SUCCESS";
export const FETCH_CURRENT_DISCUSSION_FAILURE = "FETCH_CURRENT_DISCUSSION_FAILURE";

export const SET_WAITING_FOR_CONNECTION = "SET_WAITING_FOR_CONNECTION";

export const SEND_MSG_REQUEST = "SEND_MSG_REQUEST";
export const SEND_MSG_SUCCESS = "SEND_MSG_SUCCESS";
export const SEND_MSG_FAILURE = "SEND_MSG_FAILURE";
