export const FETCH_DISCUSSIONS_OWNER_REQUEST = "FETCH_DISCUSSIONS_OWNER_REQUEST";
export const FETCH_DISCUSSIONS_OWNER_SUCCESS = "FETCH_DISCUSSIONS_OWNER_SUCCESS";
export const FETCH_DISCUSSIONS_OWNER_FAILURE = "FETCH_DISCUSSIONS_OWNER_FAILURE";

export const FETCH_DISCUSSIONS_TRAVELLER_REQUEST = "FETCH_DISCUSSIONS_TRAVELLER_REQUEST";
export const FETCH_DISCUSSIONS_TRAVELLER_SUCCESS = "FETCH_DISCUSSIONS_TRAVELLER_SUCCESS";
export const FETCH_DISCUSSIONS_TRAVELLER_FAILURE = "FETCH_DISCUSSIONS_TRAVELLER_FAILURE";

export const FETCH_CURRENT_DISCUSSION_REQUEST = "FETCH_CURRENT_DISCUSSION_REQUEST";
export const FETCH_CURRENT_DISCUSSION_SUCCESS = "FETCH_CURRENT_DISCUSSION_SUCCESS";
export const FETCH_CURRENT_DISCUSSION_FAILURE = "FETCH_CURRENT_DISCUSSION_FAILURE";
