export const USER_REQUEST = "USER_REQUEST";
export const USER_GET_ME_REQUEST = "USER_GET_ME_REQUEST";
export const LOGOUT = "LOGOUT";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const FETCH_USER_ACCOMMODATIONS_SUCCESS = "FETCH_USER_ACCOMMODATIONS_SUCCESS";
export const FETCH_USER_ACCOMMODATIONS_FAIL = "FETCH_USER_ACCOMMODATIONS_FAIL";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const CLEAN_FETCHED_USER = "CLEAN_FETCHED_USER";

